import 'dart:async';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import '../core/enums.dart';
import '../core/logger.dart';

class WebRTCStats {
  final int width;
  final int height;
  final double fps;
  final int bitrateKbps;
  final int roundTripTimeMs;

  const WebRTCStats({
    this.width = 0,
    this.height = 0,
    this.fps = 0.0,
    this.bitrateKbps = 0,
    this.roundTripTimeMs = 0,
  });
}

class WebRTCService {
  RTCPeerConnection? _peerConnection;
  MediaStream? _localStream;
  RTCVideoRenderer? _remoteRenderer;

  final StreamController<MirrorSessionState> _stateController = StreamController<MirrorSessionState>.broadcast();
  final StreamController<RTCIceCandidate> _iceCandidateController = StreamController<RTCIceCandidate>.broadcast();
  final StreamController<WebRTCStats> _statsController = StreamController<WebRTCStats>.broadcast();

  Timer? _statsTimer;
  int _lastBytesReceived = 0;
  DateTime? _lastStatsTime;

  Stream<MirrorSessionState> get onStateChange => _stateController.stream;
  Stream<RTCIceCandidate> get onIceCandidate => _iceCandidateController.stream;
  Stream<WebRTCStats> get onStats => _statsController.stream;

  Map<String, dynamic> _iceServers = {
    'iceServers': [
      {'urls': 'stun:stun.l.google.com:19302'},
      {'urls': 'stun:stun1.l.google.com:19302'},
      // Temporary TURN credentials injected dynamically from backend for 4G/5G traversal
    ],
    'sdpSemantics': 'unified-plan',
  };

  void updateTurnCredentials(List<Map<String, dynamic>> turnServers) {
    _iceServers['iceServers'] = [
      {'urls': 'stun:stun.l.google.com:19302'},
      ...turnServers,
    ];
    AppLogger.webrtc('Updated ICE server configuration with backend TURN servers');
  }

  Future<void> initializePeerConnection({required bool isSender}) async {
    AppLogger.webrtc('Initializing RTCPeerConnection (isSender: $isSender)');
    
    final config = {
      ..._iceServers,
      'mandatory': {},
      'optional': [
        {'DtlsSrtpKeyAgreement': true},
      ],
    };

    _peerConnection = await createPeerConnection(config);

    _peerConnection?.onIceCandidate = (RTCIceCandidate candidate) {
      AppLogger.webrtc('Gathered local ICE candidate: ${candidate.candidate.substring(0, 30)}...');
      _iceCandidateController.add(candidate);
    };

    _peerConnection?.onConnectionState = (RTCPeerConnectionState state) {
      AppLogger.webrtc('PeerConnection state changed: $state');
      switch (state) {
        case RTCPeerConnectionState.RTCPeerConnectionStateConnecting:
          _stateController.add(MirrorSessionState.connecting);
          break;
        case RTCPeerConnectionState.RTCPeerConnectionStateConnected:
          _stateController.add(MirrorSessionState.connected);
          _startStatsMonitoring();
          break;
        case RTCPeerConnectionState.RTCPeerConnectionStateDisconnected:
          _stateController.add(MirrorSessionState.disconnected);
          break;
        case RTCPeerConnectionState.RTCPeerConnectionStateFailed:
          _stateController.add(MirrorSessionState.failed);
          break;
        case RTCPeerConnectionState.RTCPeerConnectionStateClosed:
          _stateController.add(MirrorSessionState.ended);
          _stopStatsMonitoring();
          break;
        default:
          break;
      }
    };

    if (!isSender) {
      _peerConnection?.onTrack = (RTCTrackEvent event) {
        AppLogger.webrtc('Received remote video track: ${event.track.id}');
        if (event.streams.isNotEmpty && _remoteRenderer != null) {
          _remoteRenderer?.srcObject = event.streams[0];
        }
      };
    }
  }

  /// CHILD (SENDER): Attaches the native screen media stream into WebRTC
  Future<void> attachLocalScreenStream(MediaStream stream) async {
    _localStream = stream;
    for (var track in stream.getVideoTracks()) {
      AppLogger.webrtc('Adding screen video track to PeerConnection: ${track.id}');
      await _peerConnection?.addTrack(track, stream);
    }
  }

  /// PARENT (RECEIVER): Sets the renderer for drawing the child's screen
  void attachRemoteRenderer(RTCVideoRenderer renderer) {
    _remoteRenderer = renderer;
  }

  /// Create WebRTC SDP Offer (typically generated by the Sender/Child or Parent depending on topology)
  Future<RTCSessionDescription> createOffer() async {
    AppLogger.webrtc('Creating SDP Offer');
    final constraints = {
      'mandatory': {
        'OfferToReceiveVideo': true,
        'OfferToReceiveAudio': false,
      },
      'optional': [],
    };
    final offer = await _peerConnection!.createOffer(constraints);
    await _peerConnection!.setLocalDescription(offer);
    return offer;
  }

  /// Set Remote SDP (Offer or Answer)
  Future<void> setRemoteDescription(RTCSessionDescription desc) async {
    AppLogger.webrtc('Setting remote SDP description: ${desc.type}');
    await _peerConnection?.setRemoteDescription(desc);
  }

  /// Create WebRTC SDP Answer in response to Offer
  Future<RTCSessionDescription> createAnswer() async {
    AppLogger.webrtc('Creating SDP Answer');
    final constraints = {
      'mandatory': {
        'OfferToReceiveVideo': true,
        'OfferToReceiveAudio': false,
      },
      'optional': [],
    };
    final answer = await _peerConnection!.createAnswer(constraints);
    await _peerConnection!.setLocalDescription(answer);
    return answer;
  }

  /// Add Remote ICE Candidate
  Future<void> addCandidate(RTCIceCandidate candidate) async {
    AppLogger.webrtc('Adding remote ICE candidate');
    await _peerConnection?.addCandidate(candidate);
  }

  /// Restart ICE upon network change (e.g. Wi-Fi -> Mobile Data handoff)
  Future<RTCSessionDescription> restartIce() async {
    AppLogger.webrtc('Initiating WebRTC ICE restart');
    final constraints = {
      'mandatory': {
        'IceRestart': true,
      },
    };
    final offer = await _peerConnection!.createOffer(constraints);
    await _peerConnection!.setLocalDescription(offer);
    return offer;
  }

  void _startStatsMonitoring() {
    _statsTimer?.cancel();
    _lastStatsTime = DateTime.now();
    _lastBytesReceived = 0;

    _statsTimer = Timer.periodic(const Duration(seconds: 1), (_) async {
      if (_peerConnection == null) return;
      try {
        final reports = await _peerConnection!.getStats();
        int width = 0;
        int height = 0;
        double fps = 0.0;
        int bitrate = 0;
        int rtt = 0;

        for (var report in reports) {
          if (report.type == 'inbound-rtp' && report.values['kind'] == 'video') {
            final bytes = int.tryParse(report.values['bytesReceived']?.toString() ?? '0') ?? 0;
            final now = DateTime.now();
            if (_lastStatsTime != null) {
              final ms = now.difference(_lastStatsTime!).inMilliseconds;
              if (ms > 0) {
                final deltaBytes = bytes - _lastBytesReceived;
                bitrate = ((deltaBytes * 8) / (ms / 1000) / 1000).toInt();
              }
            }
            _lastBytesReceived = bytes;
            _lastStatsTime = now;

            fps = double.tryParse(report.values['framesPerSecond']?.toString() ?? '0.0') ?? 0.0;
            width = int.tryParse(report.values['frameWidth']?.toString() ?? '1280') ?? 1280;
            height = int.tryParse(report.values['frameHeight']?.toString() ?? '720') ?? 720;
          }

          if (report.type == 'candidate-pair' && report.values['state'] == 'succeeded') {
            final roundTrip = double.tryParse(report.values['currentRoundTripTime']?.toString() ?? '0') ?? 0.0;
            rtt = (roundTrip * 1000).toInt();
          }
        }

        _statsController.add(WebRTCStats(
          width: width,
          height: height,
          fps: fps,
          bitrateKbps: bitrate,
          roundTripTimeMs: rtt,
        ));
      } catch (e) {
        // stats error
      }
    });
  }

  void _stopStatsMonitoring() {
    _statsTimer?.cancel();
    _statsTimer = null;
  }

  Future<void> dispose() async {
    _stopStatsMonitoring();
    await _localStream?.dispose();
    await _peerConnection?.close();
    _peerConnection = null;
    _stateController.close();
    _iceCandidateController.close();
    _statsController.close();
  }
}
