-- =========================================================================
-- SCREENMIRROR: BACKEND POSTGRESQL SCHEMA WITH ROW-LEVEL SECURITY (RLS)
-- Remote screen-mirroring parental control system.
-- =========================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE (Parent & Child accounts)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('parent', 'child')),
    display_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. DEVICES TABLE
CREATE TABLE IF NOT EXISTS public.devices (
    id TEXT PRIMARY KEY, -- Device UUID generated by device on first run
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    device_name TEXT NOT NULL,
    platform TEXT NOT NULL DEFAULT 'android',
    android_version TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    model TEXT NOT NULL,
    fcm_token TEXT,
    presence_state TEXT NOT NULL DEFAULT 'READY' CHECK (
        presence_state IN ('ONLINE', 'OFFLINE', 'READY', 'MIRRORING', 'RECONNECTING', 'AUTHORIZATION_REQUIRED', 'UNAVAILABLE')
    ),
    is_battery_exempted BOOLEAN NOT NULL DEFAULT FALSE,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. PARENT-CHILD LINKS (Verified cryptographic relationships)
CREATE TABLE IF NOT EXISTS public.parent_child_links (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    parent_user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    child_device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    child_nickname TEXT,
    paired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(parent_user_id, child_device_id)
);

-- 4. PAIRING CODES (Short-lived 6-digit or QR codes)
CREATE TABLE IF NOT EXISTS public.pairing_codes (
    code TEXT PRIMARY KEY,
    child_device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    child_device_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '10 minutes'),
    is_claimed BOOLEAN NOT NULL DEFAULT FALSE,
    claimed_by_parent_id UUID REFERENCES public.users(id)
);

-- 5. MIRRORING SESSIONS (Full audit trail of all screen sessions)
CREATE TABLE IF NOT EXISTS public.mirroring_sessions (
    id TEXT PRIMARY KEY,
    parent_id UUID NOT NULL REFERENCES public.users(id),
    child_device_id TEXT NOT NULL REFERENCES public.devices(id),
    status TEXT NOT NULL DEFAULT 'REQUESTED' CHECK (
        status IN ('REQUESTED', 'ACCEPTED', 'REJECTED', 'CONNECTING', 'STREAMING', 'RECONNECTING', 'ENDED', 'REVOKED', 'FAILED')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    termination_reason TEXT,
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. SIGNALING MESSAGES (Real-time SDP Offers, Answers, and ICE Candidates)
CREATE TABLE IF NOT EXISTS public.signaling_messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id TEXT NOT NULL REFERENCES public.mirroring_sessions(id) ON DELETE CASCADE,
    sender_id TEXT NOT NULL,
    target_device_id TEXT NOT NULL,
    message_type TEXT NOT NULL CHECK (message_type IN ('offer', 'answer', 'ice_candidate', 'session_end', 'reconnect_offer')),
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- ROW-LEVEL SECURITY (RLS) POLICIES
-- =========================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parent_child_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pairing_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mirroring_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signaling_messages ENABLE ROW LEVEL SECURITY;

-- USERS POLICIES
CREATE POLICY "Users can view own profile"
    ON public.users FOR SELECT
    USING (auth.uid() = id);

-- DEVICES POLICIES
CREATE POLICY "Users can view own registered devices"
    ON public.devices FOR SELECT
    USING (user_id = auth.uid());

CREATE POLICY "Parents can view their linked child devices"
    ON public.devices FOR SELECT
    USING (
        id IN (
            SELECT child_device_id FROM public.parent_child_links
            WHERE parent_user_id = auth.uid() AND is_active = TRUE
        )
    );

CREATE POLICY "Devices can update own presence"
    ON public.devices FOR UPDATE
    USING (id = current_setting('request.jwt.claim.device_id', true));

-- PARENT-CHILD LINKS POLICIES
CREATE POLICY "Parents can view their active child links"
    ON public.parent_child_links FOR SELECT
    USING (parent_user_id = auth.uid());

-- PAIRING CODES POLICIES
CREATE POLICY "Anyone authenticated can create pairing code for own device"
    ON public.pairing_codes FOR INSERT
    WITH CHECK (TRUE);

CREATE POLICY "Parents can view valid pairing codes"
    ON public.pairing_codes FOR SELECT
    USING (expires_at > NOW() AND is_claimed = FALSE);

-- MIRRORING SESSIONS POLICIES
CREATE POLICY "Parents can view and create sessions with linked child devices"
    ON public.mirroring_sessions FOR ALL
    USING (
        parent_id = auth.uid() AND
        child_device_id IN (
            SELECT child_device_id FROM public.parent_child_links
            WHERE parent_user_id = auth.uid() AND is_active = TRUE
        )
    );

CREATE POLICY "Child devices can view and update their own sessions"
    ON public.mirroring_sessions FOR ALL
    USING (child_device_id = current_setting('request.jwt.claim.device_id', true));

-- SIGNALING MESSAGES POLICIES
CREATE POLICY "Participants can exchange signaling packets"
    ON public.signaling_messages FOR ALL
    USING (
        session_id IN (
            SELECT id FROM public.mirroring_sessions
            WHERE parent_id = auth.uid() OR child_device_id = current_setting('request.jwt.claim.device_id', true)
        )
    );

-- =========================================================================
-- SECURE RPC FUNCTIONS
-- =========================================================================

-- Function: Claim Pairing Code (Executes atomic parent-child linking)
CREATE OR REPLACE FUNCTION public.claim_pairing_code(p_code TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_record RECORD;
    v_parent_id UUID;
BEGIN
    v_parent_id := auth.uid();
    IF v_parent_id IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: Parent must be authenticated.';
    END IF;

    SELECT * INTO v_record
    FROM public.pairing_codes
    WHERE code = p_code AND is_claimed = FALSE AND expires_at > NOW()
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'Invalid or expired pairing code.');
    END IF;

    -- Mark code claimed
    UPDATE public.pairing_codes
    SET is_claimed = TRUE, claimed_by_parent_id = v_parent_id
    WHERE code = p_code;

    -- Insert or activate parent-child link
    INSERT INTO public.parent_child_links (parent_user_id, child_device_id, child_nickname)
    VALUES (v_parent_id, v_record.child_device_id, v_record.child_device_name)
    ON CONFLICT (parent_user_id, child_device_id)
    DO UPDATE SET is_active = TRUE;

    RETURN jsonb_build_object(
        'success', true,
        'child_device_id', v_record.child_device_id,
        'child_device_name', v_record.child_device_name
    );
END;
$$;

-- Function: Validate session initiation request
CREATE OR REPLACE FUNCTION public.validate_session_request(p_child_device_id TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.parent_child_links
        WHERE parent_user_id = auth.uid()
          AND child_device_id = p_child_device_id
          AND is_active = TRUE
    );
END;
$$;

-- =========================================================================
-- REALTIME REPLICATION CONFIGURATION
-- =========================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        CREATE PUBLICATION supabase_realtime;
    END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.signaling_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.mirroring_sessions;
